on: push


name: Integration


jobs:
    build:
         runs-on: ubuntu-latest #runs on require 
         steps: # steps require
            - uses: actions/checkout@v2 # use exactly script
            - run: |
               echo abc
               echo pdf
   
    docker-build:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
         - uses: actions/checkout@v2 # use exactly script
         - name: Build
           run: |
            docker build .
            docker image ls

            
    
    